### ISSUE TITLE
No language mode?

### ISSUE THREAD

**Issue by gplastic** [tboby/cwtools-vscode#1]
I'm looking for the language mode with this extension, but I can't find it.

**Comment by tboby** [comment]
The language is called "paradox". The extension will automatically activate on files that match the pattern `**/stellaris/**/*.txt`, or when you change to language paradox manually.

When it activates it'll treat the current folder as the mod folder, so open your mod folder directly!

**Comment by tboby** [comment]
There are now a number of language modes
