### ISSUE TITLE
CW241 Unexpected Node 

### ISSUE THREAD

**Issue by juliemars** [tboby/cwtools-vscode#4]
Hi

I am working on a Mod, and I am getting a message [CW241] Unexpected Node heir_title_female in ruler [CW241] 

I have checked by creating an empire in game and this is the correct name to use for Female heir's. 
heir_title_female ="Princess Royal"

Any ideas? I know I can safely ignore this but wanted to check if it's something obvious.

**Comment by tboby** [comment]
Is this in a prescripted country? The rules for that block are defined here: https://github.com/tboby/cwtools-stellaris-config/blob/37acbf18ddb1a9e38de0cc121d6bb349c9ca9f23/config/prescripted_countries/prescripted_countries.cwt#L102

It looks like it's only got heir_title not female. If it works feel free to make a pull request with the change, or I can update the rules :)

Is there anywhere else you can specify that?

**Comment by tboby** [comment]
Merged your pull request. You can get that update straight away if you change the setting "rules_version" to "latest". Otherwise it'll be in the next "stable" release :)
